//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOITRA
    {
        public string MaDTra { get; set; }
        public string IDKH { get; set; }
        public string IDGIAY { get; set; }
        public string MaHDB { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<System.DateTime> NgayDoitra { get; set; }
        public string Xuly { get; set; }
    
        public virtual GIAY GIAY { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual HDB HDB { get; set; }
    }
}
