//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY
    {
        public GIAY()
        {
            this.CTHDBs = new HashSet<CTHDB>();
            this.CTHDNs = new HashSet<CTHDN>();
            this.DOITRAs = new HashSet<DOITRA>();
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string IDGIAY { get; set; }
        public string Tengiay { get; set; }
        public string Loaigiay { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Size { get; set; }
        public string Mausac { get; set; }
        public string IDNCC { get; set; }
        public Nullable<int> DongiaN { get; set; }
        public Nullable<int> DongiaB { get; set; }
        public string Anh { get; set; }
    
        public virtual ICollection<CTHDB> CTHDBs { get; set; }
        public virtual ICollection<CTHDN> CTHDNs { get; set; }
        public virtual ICollection<DOITRA> DOITRAs { get; set; }
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
