//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDN
    {
        public HDN()
        {
            this.CTHDNs = new HashSet<CTHDN>();
        }
    
        public string MaHDN { get; set; }
        public System.DateTime Ngaylap { get; set; }
        public string IDNV { get; set; }
        public string IDNCC { get; set; }
        public Nullable<int> Thanhtien { get; set; }
    
        public virtual ICollection<CTHDN> CTHDNs { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
