//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DOITRAs = new HashSet<DOITRA>();
            this.DONHANGs = new HashSet<DONHANG>();
            this.THEKHs = new HashSet<THEKH>();
        }
    
        public string IDKH { get; set; }
        public string tenkhachhang { get; set; }
        public bool gioitinh { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<DOITRA> DOITRAs { get; set; }
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual ICollection<THEKH> THEKHs { get; set; }
    }
}
