//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHE
    {
        public LOAITHE()
        {
            this.THEKHs = new HashSet<THEKH>();
        }
    
        public string MaLoai { get; set; }
        public string Tenloai { get; set; }
        public string DT { get; set; }
    
        public virtual ICollection<THEKH> THEKHs { get; set; }
    }
}
