//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC
    {
        public NCC()
        {
            this.HDNs = new HashSet<HDN>();
        }
    
        public string IDNCC { get; set; }
        public string TenNCC { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
    
        public virtual ICollection<HDN> HDNs { get; set; }
    }
}
