//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.DONHANGs = new HashSet<DONHANG>();
            this.HDNs = new HashSet<HDN>();
        }
    
        public string IDNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string cmt { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string bophan { get; set; }
        public bool gioitinh { get; set; }
        public string taikhoan { get; set; }
    
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual ICollection<HDN> HDNs { get; set; }
    }
}
